export const SET_CONSIGNOR_PROFILE = 'SET_CONSIGNOR_PROFILE';
export const SET_CONSIGNEE_PROFILE = 'SET_CONSIGNEE_PROFILE';
export const SET_TRANSPORTER_PROFILE = 'SET_TRANSPORTER_PROFILE';
export const SET_CONSIGNOR_ADDRESS = 'SET_CONSIGNOR_ADDRESS';
export const SET_CONSIGNEE_LIST = 'SET_CONSIGNEE_LIST';
export const SET_SUPERVISOR_LIST = 'SET_SUPERVISOR_LIST';
export const SET_CITY_LIST = 'SET_CITY_LIST';
